# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
scan_timeout = 10
command_timeout = 500

[package]
disabled = true

[git_branch]
# symbol = "ï˜ "
symbol = ""
format = '\([$symbol$branch(:$remote_branch)]($style)\)'

[git_status]
format = '([$all_status$ahead_behind]($style) ) '
up_to_date = 'âœ“'
stashed = ''
ignore_submodules = true
untracked = ""

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[aws]
disabled = true
format = "on [$symbol$profile]($style) "
symbol = "ğŸ…° "

[gcloud]
disabled = true
format = 'on [$symbol$active(\($account\))]($style) '
symbol = "ğŸ…¶ "

[docker_context]
disabled = true

[directory]
truncation_length = 3
