# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
scan_timeout = 10
command_timeout = 300

[git_branch]
symbol = "ï˜ "

[aws]
format = "on [$symbol$profile]($style) "
symbol = "ğŸ…° "

[gcloud]
format = 'on [$symbol$active(\($account\))]($style) '
symbol = "ğŸ…¶ "
